name: Build Android APK Online

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: '21'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK 37
        run: sdkmanager "platforms;android-37"

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build APK dengan Gradle
        run: ./gradlew assembleDebug

      - name: Upload File APK Jadi
        uses: actions/upload-artifact@v4
        with:
          name: AABrowser-In-Motion-Debug
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
